const express=require('express');const http=require('http');const {Server}=require('socket.io');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.json());app.use(express.static(path.join(__dirname,'../public')));
const zones=['Guadalupe','Chepén'];let orders=[];let next=1001;const drivers=new Map();
const zoneOf=a=>/chep[eé]n/i.test(a)?'Chepén':/guadalupe/i.test(a)?'Guadalupe':null;
app.get('/api/orders',(q,r)=>r.json(orders));
app.post('/api/orders',(q,r)=>{const {customer,address,items,total,zone}=q.body;const z=zoneOf(address)||zone;if(!z)return r.status(400).json({error:'Solo atendemos Guadalupe y Chepén.'});const o={id:next++,customer:customer||'Cliente',address,address,zone:z,items:items||[],total:Number(total)||0,status:'RECIBIDO',driverId:null,lat:null,lng:null,createdAt:Date.now()};orders.unshift(o);io.emit('order:update',o);r.json(o)});
app.patch('/api/orders/:id',(q,r)=>{const o=orders.find(x=>x.id==q.params.id);if(!o)return r.sendStatus(404);Object.assign(o,q.body);io.emit('order:update',o);r.json(o)});
io.on('connection',s=>{s.emit('orders:init',orders);s.emit('drivers:init',[...drivers.values()]);s.on('driver:join',d=>{drivers.set(s.id,{id:s.id,name:d.name||'Repartidor',zone:d.zone||'Guadalupe',lat:null,lng:null});io.emit('drivers:update',[...drivers.values()])});s.on('driver:location',p=>{if(!p||!Number.isFinite(p.lat)||!Number.isFinite(p.lng))return;const d=drivers.get(s.id);if(d){d.lat=p.lat;d.lng=p.lng;d.zone=p.zone||d.zone;io.emit('driver:location',{driverId:s.id,...p})}const o=orders.find(x=>x.id==p.orderId);if(o){o.lat=p.lat;o.lng=p.lng;o.driverId=s.id;o.status=o.status==='RECIBIDO'||o.status==='PREPARANDO'?'EN CAMINO':o.status;io.emit('order:update',o)}});s.on('driver:leave',()=>{drivers.delete(s.id);io.emit('drivers:update',[...drivers.values()])});s.on('disconnect',()=>{drivers.delete(s.id);io.emit('drivers:update',[...drivers.values()])})});
server.listen(process.env.PORT||3000,()=>console.log('Punto Verde Express: Guadalupe + Chepén'));
